<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Sign In · Puihaha Electric</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet">
    <style>
        :root{--blue:#1769aa;--blue-dark:#0b3d70}*{box-sizing:border-box}.login-page{min-height:100vh;background:#9fc8e8;display:grid;place-items:center;padding:24px;font-family:Inter,system-ui,sans-serif}.login-shell{width:min(1060px,100%);min-height:600px;display:grid;grid-template-columns:1.15fr .85fr;border-radius:20px;overflow:hidden;background:#fff;box-shadow:0 24px 60px #0b3d7055}.login-art{position:relative;overflow:hidden;padding:70px 68px;color:#fff;background:linear-gradient(140deg,#55a9e2,#1769aa 52%,#0b3d70)}.login-art:before,.login-art:after{content:"";position:absolute;border:1px solid #fff8;border-radius:48%;transform:rotate(-24deg);box-shadow:0 0 0 24px #fff1,0 0 0 48px #fff0}.login-art:before{width:390px;height:270px;left:-120px;top:-20px}.login-art:after{width:430px;height:300px;right:-170px;bottom:-60px}.dots{position:absolute;right:48px;top:34px;width:42px;height:120px;background:radial-gradient(circle,#fff 2px,transparent 3px);background-size:14px 14px}.login-copy{position:relative;z-index:1;margin-top:125px}.login-copy h1{font-size:2.7rem;font-weight:800;margin:25px 0 10px}.login-copy p{font-size:1.1rem;max-width:410px;line-height:1.55}.login-form{display:flex;flex-direction:column;justify-content:center;padding:70px 68px}.login-form h2{font-size:2.3rem;font-weight:800;margin-bottom:30px}.field{position:relative;margin-bottom:16px}.field i{position:absolute;left:18px;top:17px;color:#aaa}.field input{height:54px;border-radius:28px;padding-left:46px}.login-options{display:flex;justify-content:space-between;font-size:.82rem;color:#777;margin:3px 3px 28px}.login-options a,.login-new a{color:var(--blue);text-decoration:none;font-weight:700}.login-button{height:54px;border:0;border-radius:28px;color:#fff;font-weight:700;font-size:1rem;background:linear-gradient(100deg,#0b3d70,#2384c8);box-shadow:0 10px 20px #1769aa35}.login-new{text-align:center;font-size:.85rem;color:#777;margin-top:25px}.alert{font-size:.82rem;border-radius:10px}@media(max-width:760px){.login-shell{grid-template-columns:1fr}.login-art{min-height:260px;padding:35px}.login-copy{margin-top:30px}.login-copy h1{font-size:2rem}.login-form{padding:40px 30px}}
    .back-home{display:block;text-align:center;margin-top:14px;color:var(--blue);font-size:.85rem;font-weight:700;text-decoration:none}.back-home:hover{text-decoration:underline}</style>
</head>
<body class="login-page"><main class="login-shell"><section class="login-art"><div class="dots"></div><div class="login-copy"><div class="text-uppercase small fw-bold"><i class="bi bi-lightning-charge-fill me-2"></i>Puihaha Electric</div><h1>Welcome back!</h1><p>You can sign in to access your customer account workspace.</p></div></section><section class="login-form"><h2>Sign In</h2><?php if($message=session()->getFlashdata('error')): ?><div class="alert alert-danger"><?= esc($message) ?></div><?php endif; ?><?php if($message=session()->getFlashdata('success')): ?><div class="alert alert-success"><?= esc($message) ?></div><?php endif; ?><form action="<?= base_url('login') ?>" method="post"><?= csrf_field() ?><label class="small fw-semibold" for="email">Username or email</label><div class="field"><i class="bi bi-person-fill"></i><input class="form-control" id="email" name="email" type="email" placeholder="Username or email" value="<?= esc(old('email')) ?>" required autofocus></div><label class="small fw-semibold" for="password">Password</label><div class="field"><i class="bi bi-lock-fill"></i><input class="form-control" id="password" name="password" type="password" placeholder="Password" required></div><div class="login-options"><label><input type="checkbox"> Remember me</label><a href="<?= base_url('contact') ?>">Forgot password?</a></div><button class="login-button w-100" type="submit">Sign In</button></form><p class="login-new">New here? <a href="<?= base_url('register') ?>">Create an Account</a></p><a class="back-home" href="<?= base_url() ?>"><i class="bi bi-arrow-left me-1"></i>Back to Home</a></section></main></body></html>
